//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Animal.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//

package Modelo;

public abstract class Animal {
	private String imagen;
	private String nombre;
	protected Posicion posicion; 
	
	public void nombrar(String nombre) {
		this.nombre = nombre;
	}
	
	public abstract void moverAnimal(int direccion, Contexto contexto);
	
	public abstract int calcularDano(Elemento elemento);
	
	public abstract boolean soyElAnimal(int tipoAnimal);
}
