//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroirde.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//

package Modelo;


public class Asteroide extends Danino {
	private int puntaje;

	public void calcularDano(Mamifero m) {
		
	}

	public void calcularDano(Ave a) {
		
	}

	public void calcularDano(Reptil r) {
		
	}
}
