//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Movimiento.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//


package Modelo;

public abstract class Movimiento {
	public abstract Posicion calcularPosicion(Posicion posicion, Dificultad dificultad);
}
