//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Zigzag.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//


package Modelo;

public class Zigzag extends Movimiento {
	public Posicion calcularPosicion(Posicion posicion, Dificultad dificultad) {
		return null;
	}
}
