//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Benéfico.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//

package Modelo;


public abstract class Benefico extends Elemento {
	public abstract void calcularDano(Mamifero m);
	public abstract void calcularDano(Ave a);
	public abstract void calcularDano(Reptil r);
}
