//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Contexto.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//


package Modelo;

public abstract class Contexto {
	public abstract float calcularVelocidad(Mamifero m);
	public abstract float calcularVelocidad(Ave a);
	public abstract float calcularVelocidad(Reptil r);
	public abstract boolean soyElContexto(int tipoContexto);
}
