//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Elemento.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//

package Modelo;

public abstract class Elemento {
	private String imagen;
	protected Movimiento movimiento;
	private Posicion posicion;
	
	public Elemento(){
		this.posicion = new Posicion(0,0);
	}
	
	public void moverElemento(Dificultad dificultad) {
		this.posicion = movimiento.calcularPosicion(posicion, dificultad);
	}
	
	public abstract void calcularDano(Mamifero m);
	
	public abstract void calcularDano(Ave a);
	
	public abstract void calcularDano(Reptil r);
	
	public void determinarMovimiento(Movimiento m) {
		this.movimiento = m; 
	}
}
