//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Fruta.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//

package Modelo;


public class Fruta extends Benefico {
	private int puntaje;
	public void calcularDano(Mamifero m) {
	
	}
	
	public void calcularDano(Ave a) {
	
	}
	
	public void calcularDano(Reptil r) {
	
	}
}
