//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Juego.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//


package Modelo;

public class Juego {
	private Dificultad dificultad;
	public int puntaje;
	public Elemento listaElementos;
	public void elegirAnimal(int tipoAnimal) {
	
	}
	
	public void elegirDificultad(Dificultad dificultad) {
	
	}
	
	public void elegirContexto(int tipoContexto) {
	
	}
	
	public void ingresarNombre() {
	
	}
	
	public int calcularPuntaje(int puntaje, int calcularDaño) {
		return 0;
	}
	
	public void obtenerAnimal() {
	
	}
	
	public void obtenerContexto() {
	
	}
	
	public void obtenerDificultad() {
	
	}
	
	public void determinarMovimiento() {
	
	}
	
	public void moverAnimal() {
	
	}
}
