//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Posicion.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//


package Modelo;

public class Posicion {
	private int x;
	private int y;
	
	public Posicion(int x, int y){
		this.x = x;
		this.y = y;
	}
	
	public int obtenerX() {
		return x;
	}
	
	public int obtenerY() {
		return y;
	}
}
