//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sistema.java
//  @ Date : 28/05/2015
//  @ Author : 
//
//


package Modelo;

public class Sistema {
	private Object listaMovimientos;
	private Object listaContextos;
	private Object listaPartidas;
	public void almacenarPuntaje(int puntaje) {
	
	}
}
